server.error.whitelabel.enabled=false
server.servlet.session.timeout=15m
#DB settings bloipthis55%
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Database standard connection info
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bloip?serverTimezone=UTC
spring.datasource.username=bloip2
spring.datasource.password=bloip2
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=false

#App specific properties
app.discussionsPerPage=2
app.inboxItemsPerPage=2
app.commentsPerPage=2
app.maxTitleLength=40

#Infrastructure
app.baseURL = http://localhost:8080

app.audioBucketURL = https://bloipe-audio-test.s3.amazonaws.com