
#Logging
logging.file.name=bloip.log
logging.level.com.bloip.services.LoggingService=DEBUG
#logging.level.org.springframework.security=DEBUG

#HTTPS Configuration
server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore/bloip.p12
server.ssl.key-store=${KEY_STORE_LOCATION}
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
server.ssl.key-alias=bloip
server.ssl.enabled=true
server.port=8443

#Server Settings
server.error.whitelabel.enabled=false
server.servlet.session.timeout=15m

#Database
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=${HIBERNATE_DIALECT}
#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
#spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8InnoDBDialect
spring.jpa.show-sql=false

# Database connection pool properties
#spring.r2dbc.pool.enabled=true
#spring.r2dbc.pool.initial-size=50
#spring.r2dbc.pool.max-size=100

#Application Specific Properties
app.selectedHbmDialect=${HIBERNATE_DIALECT}
app.environment=${ENVIRONMENT}
app.assetVersion=1.0
app.enableRemoteServices=${ENABLE_REMOTE_SERVICES}
app.discussionsPerPage=2
app.inboxItemsPerPage=2
app.commentsPerPage=2
app.maxDiscussionCreationsPerDay=10

#Webpush
app.applicationServerKey=${VAPID_PUBLIC_KEY}
app.vapidPrivateKey=${VAPID_PRIVATE_KEY}
app.webPushRunnerCheckTime=5000
app.webPushCountWindowHours=24
app.webPushMinimumResponseDelayMin=30
app.webPushDailyCountMax=10

#Infrastructure
app.baseUrl = ${BASE_URL}

#S3
app.awsUploadRegion=us-east-1
app.awsUploadBucketName=${AWS_S3_UPLOAD_BUCKET_NAME}
app.awsUploadSecretKey=${AWS_UPLOAD_SECRET_KEY}
app.awsUploadAccessKey=${AWS_UPLOAD_ACCESS_KEY}
app.awsPolicyDurationHours=12
app.awsS3RedirectUrl=${AWS_S3_REDIRECT_URL}
app.audioCdnRootUrl=${AUDIO_CDN_ROOT_URL}
app.audioCdnUploadUrl=${AUDIO_CDN_UPLOAD_URL}
app.emailBucket=${EMAIL_BUCKET}

app.mediaConvertRole=${MEDIA_CONVERT_ROLE}
app.needsConversionQueueUrl=${NEEDS_CONVERSION_QUEUE_URL}
app.conversionCompleteQueueUrl=${CONVERSION_COMPLETE_QUEUE_URL}
app.maxAudioQueueBatchSize=10
app.audioConversionConsumerThreadSleepMillis=5000

app.eventQueueUrl=${EVENT_QUEUE_URL}
app.eventTopic=${EVENT_TOPIC}
app.errorQueueUrl=${ERROR_QUEUE_URL}
app.errorTopic=${ERROR_TOPIC}
app.eventNotificationInterval = ${EVENT_NOTIFICATION_INTERVAL}
app.emailQueueUrl=${EMAIL_QUEUE_URL}
app.emailQueuePollInterval=5000

app.shogunUsername=${SHOGUN_USERNAME}
app.shogunPassword=${SHOGUN_PASSWORD}
app.serviceEmailAddress=${SERVICE_EMAIL_ADDRESS}

app.mscCdn=${MSC_CDN}
app.viewVersion=${VIEW_VERSION}