
#HTTPS Configuration
server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore/bloip.p12
server.ssl.key-store=${KEY_STORE_LOCATION}
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
server.ssl.key-alias=bloip
server.ssl.enabled=true

#Server Settings
server.error.whitelabel.enabled=false
server.servlet.session.timeout=15m

#Database
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bloip?serverTimezone=UTC
spring.datasource.username=bloip2
spring.datasource.password=bloip2
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.show-sql=false

#Application Specific Properties
app.enableRemoteServices=${ENABLE_REMOTE_SERVICES}
app.discussionsPerPage=2
app.inboxItemsPerPage=2
app.commentsPerPage=2
app.maxTitleLength=${MAX_TITLE_LENGTH}

#Webpush
app.applicationServerKey=${VAPID_PUBLIC_KEY}
app.vapidPrivateKey=${VAPID_PRIVATE_KEY}
app.webPushRunnerCheckTime=5000
app.webPushCountWindowHours=24
app.webPushMinimumResponseDelayMin=30
app.webPushDailyCountMax=10

#Infrastructure
app.baseUrl = ${BASE_URL}

#S3
app.awsUploadRegion=us-east-1
app.awsUploadBucketName=${AWS_S3_UPLOAD_BUCKET_NAME}
app.awsUploadSecretKey=${AWS_UPLOAD_SECRET_KEY}
app.awsUploadAccessKey=${AWS_UPLOAD_ACCESS_KEY}
app.awsPolicyDurationHours=12
app.awsS3RedirectUrl=${AWS_S3_REDIRECT_URL}
app.audioCdnRootUrl=${AUDIO_CDN_ROOT_URL}
app.audioCdnUploadUrl=${AUDIO_CDN_UPLOAD_URL}
app.mediaConvertRole=${MEDIA_CONVERT_ROLE}
app.needsConversionQueueUrl=${NEEDS_CONVERSION_QUEUE_URL}
app.conversionCompleteQueueUrl=${CONVERSION_COMPLETE_QUEUE_URL}
app.maxAudioQueueBatchSize=10
app.audioConversionConsumerThreadSleepMillis=5000